using tf stuff

diff --git a/install/tests/Makefile b/install/tests/Makefile
--- a/install/tests/Makefile
+++ b/install/tests/Makefile
@@ -7,7 +7,9 @@ TOPDIR=$(shell pwd)
 
 KUBECONFIG := "$(TOPDIR)/kubeconfig"
 
-DOMAIN := tests.gitpod-self-hosted.com
+DOMAIN := sh-tests.gitpod-self-hosted.com
+
+TF_MOD := ../infra/single-cluster/$(cloud)
 
 check-env-sub-domain:
 ifndef TF_VAR_TEST_ID
@@ -61,114 +63,62 @@ aws-kubeconfig:
 	export KUBECONFIG=${KUBECONFIG} && \
 	aws eks update-kubeconfig --name ${TF_VAR_TEST_ID} --region eu-west-1 --kubeconfig ${KUBECONFIG} || echo "No cluster present"
 
-prepare-gcp-terraform:
+
+cluster_gcp := gke
+cluster_k3s := k3s
+cluster_aws := eks
+cluster_azure := aks
+
+prepare-terraform: cluster_mod = $(cluster_$(cloud))
+prepare-terraform:
 	export DOMAIN=${DOMAIN} && \
 	export CLUSTER_VERSION=$$TF_VAR_cluster_version && \
-	export DNS_CREDENTIALS=./dns-credentials.json && \
-	envsubst < ./manifests/gcp-terraform.tfvars > ../infra/single-cluster/gcp/terraform.tfvars && \
-	envsubst < ./manifests/gcp-dns.tf > ../infra/single-cluster/gcp/gcp-dns.tf && \
-    sed -i 's/<gcs-bucket-name>/nightly-tests/' ../infra/single-cluster/gcp/main.tf && \
-    sed -i 's/gcp\/terraform.state/""/' ../infra/single-cluster/gcp/main.tf
+	export KUBECONFIG=${KUBECONFIG} && \
+	envsubst < ./manifests/$(cloud)-terraform.tfvars > $(TF_MOD)/terraform.tfvars
+	export cluster=$(cluster_mod) && \
+	envsubst < ./manifests/gcp-dns.tf > $(TF_MOD)/gcp-dns.tf
+	cp ./manifests/tf-backend.tf $(TF_MOD)/main.tf  # we set the backend to be gcs based
 
 .PHONY:
-## gke-standard-cluster: Creates a zonal GKE cluster
-gke-standard-cluster: check-env-cluster-version prepare-gcp-terraform
-	$(MAKE) -C ../infra/single-cluster/gcp/ init
-	$(MAKE) select-workspace WORKDIR=../infra/single-cluster/gcp/
-	$(MAKE) -C ../infra/single-cluster/gcp/ apply
-	terraform -chdir=../infra/single-cluster/gcp output -json > gcp-output.yaml
-	cp ../infra/single-cluster/gcp/kubeconfig .
-	cp ../infra/single-cluster/gcp/gs-credentials.json .
-	cp ../infra/single-cluster/gcp/mysql-credentials.json .
-	cp ../infra/single-cluster/gcp/dns-credentials.json .
-	terraform -chdir=../infra/single-cluster/gcp/ apply -target=module.gcp-add-dns-record --auto-approve
+## standard-cluster: Creates a kubernetes cluster of type $cloud
+standard-cluster: check-env-cloud check-env-cluster-version prepare-terraform
+	$(MAKE) -C $(TF_MOD) init
+	$(MAKE) select-workspace WORKDIR=$(TF_MOD)
+	$(MAKE) -C $(TF_MOD) apply-cluster
+	terraform -chdir=$(TF_MOD) output -json > $(cloud)-output.json
 	@echo "Done creating GKE cluster"
 
-prepare-aws-terraform:
-	export DOMAIN=${DOMAIN} && \
-	export CLUSTER_VERSION=$$TF_VAR_cluster_version && \
-	envsubst < ./manifests/aws-terraform.tfvars > ../infra/single-cluster/aws/terraform.tfvars && \
-    sed -i 's/<s3-bucket-name>/nightly-tests/' ../infra/single-cluster/aws/main.tf && \
-    sed -i 's/aws\/terraform.state/tf-state\/${TF_VAR_TEST_ID}.tfstate/' ../infra/single-cluster/aws/main.tf
-
-ami_id_121 := "ami-060637af2651bc8bb"
-ami_id_122 := "ami-0733d755ed2c97a4d"
-ami_id_123 := "ami-05ec8881b9c2740d4"
+.PHONY:
+## cert-manager: Installs cert-manager, optionally create secret for cloud-dns access
+cert-manager: check-env-cloud
+	$(MAKE) -C $(TF_MOD) init
+	$(MAKE) select-workspace WORKDIR=$(TF_MOD)
+	terraform -chdir=$(TF_MOD) apply -target=module.certmanager --auto-approve
+	@echo "Done installing cert-manager"
 
 .PHONY:
-## eks-standard-cluster: Creates an EKS cluster
-eks-standard-cluster: ami_id = $(if $(ami_id_${TF_VAR_cluster_version//.}),$(ami_id_${TF_VAR_cluster_version//.}),$(ami_id_122))
-eks-standard-cluster: check-env-cluster-version prepare-aks-terraform
-	terraform init --upgrade && \
-	terraform workspace new $(TF_VAR_TEST_ID) || $(MAKE) select-workspace && \
-	rm -f ${KUBECONFIG} && \
-	$(MAKE) get-kubeconfig && \
-	[[ -f ${KUBECONFIG} ]] || terraform apply -target=module.eks -var kubeconfig=${KUBECONFIG} -var eks_node_image_id=${ami_id} --auto-approve
-	@echo "Done creating EKS cluster"
-
-.PHONY:
-## aks-standard-cluster: Creates an AKS cluster
-aks-standard-cluster: check-env-cluster-version
-	terraform init --upgrade && \
-	terraform workspace new $(TF_VAR_TEST_ID) || $(MAKE) select-workspace && \
-	rm -f ${KUBECONFIG} && \
-	$(MAKE) get-kubeconfig && \
-	[[ -f ${KUBECONFIG} ]] || terraform apply -target=module.aks -var kubeconfig=${KUBECONFIG} --auto-approve
-	@echo "Done creating AKS cluster"
-
-.PHONY:
-## add-ns-record: Adds NS record for subdomain under gitpod-selfhosted.com
-add-ns-record: check-env-cloud
-	terraform init --upgrade && \
-	terraform workspace new $(TF_VAR_TEST_ID) || terraform workspace select $(TF_VAR_TEST_ID) && \
-	terraform apply -target=module.$(cloud)-add-dns-record  -var kubeconfig=${KUBECONFIG} --auto-approve
-	@echo "Done adding NS record"
+## external-dns: Installs external-dns
+external-dns: check-env-cloud
+	$(MAKE) -C $(TF_MOD) init
+	$(MAKE) select-workspace WORKDIR=$(TF_MOD)
+	terraform -chdir=$(TF_MOD) apply -target=module.externaldns --auto-approve
+	@echo "Done creating externaldns for $(cloud)"
 
 .PHONY:
 ## cluster-issuer: Creates a cluster issuer for the correspondign provider
 cluster-issuer: check-env-cloud
-	terraform init --upgrade && \
-	terraform workspace new $(TF_VAR_TEST_ID) || terraform workspace select $(TF_VAR_TEST_ID) && \
-	terraform apply -target=module.$(cloud)-issuer  -var kubeconfig=${KUBECONFIG} --auto-approve
+	$(MAKE) -C $(TF_MOD) init
+	$(MAKE) select-workspace WORKDIR=$(TF_MOD)
+	$(MAKE) -C $(TF_MOD) install-cluster-issuer
 	@echo "Done creating cluster issuer"
 
-image_id_1804 := "ubuntu-1804-bionic-v20220712"
-
-image_id_2004 := "ubuntu-2004-focal-v20220712"
-
-image_id_2204 := "ubuntu-2204-jammy-v20220712a"
-
-os_version ?= "2004"
 .PHONY:
-## k3s-standard-cluster: Creates a K3S cluster on GCP with one master and 1 worker node
-k3s-standard-cluster: image_id = $(if $(image_id_$(os_version)),$(image_id_$(os_version)),$(image_id_2004))
-k3s-standard-cluster: check-env-cluster-version
-	terraform init --upgrade && \
-	terraform workspace new $(TF_VAR_TEST_ID) || $(MAKE) select-workspace && \
-	rm -f ${KUBECONFIG} && \
-	$(MAKE) get-kubeconfig && \
-	[[ -f ${KUBECONFIG} ]] || terraform apply -target=module.k3s -var kubeconfig=${KUBECONFIG} -var k3s_node_image_id=${image_id} --auto-approve && \
-	$(MAKE) upload-kubeconfig-to-gcp # we upload the file to GCP since we cannot retrieve the file against without SSHing to the master
-	@echo "Done creating k3s cluster"
-
-.PHONY:
-## cert-manager: Installs cert-manager, optionally create secret for cloud-dns access
-cert-manager:
-	$(MAKE) select-workspace && \
-	terraform apply -target=module.certmanager -var kubeconfig=${KUBECONFIG} --auto-approve
-	@echo "Done installing cert-manager"
-
-.PHONY:
-## managed-dns: Installs external-dns, and setup up CloudDNS access
-managed-dns: check-env-sub-domain select-workspace
-	terraform apply -target=module.clouddns-externaldns -var kubeconfig=${KUBECONFIG} --auto-approve
-	@echo "Done created GCP managed DNS"
-
-.PHONY:
-## external-dns: Installs external-dns
-external-dns: check-env-cloud select-workspace
-	terraform apply -target=module.$(cloud)-externaldns -var kubeconfig=${KUBECONFIG} --auto-approve
-	@echo "Done creating externaldns for $(cloud)"
+## add-ns-record: Adds NS record for subdomain under gitpod-selfhosted.com
+add-ns-record: check-env-cloud prepare-terraform
+	$(MAKE) -C $(TF_MOD) init
+	$(MAKE) select-workspace WORKDIR=$(TF_MOD)
+	terraform -chdir=$(TF_MOD) apply -target=module.add-dns-record --auto-approve
+	@echo "Done adding NS record"
 
 .PHONY:
 ## get-kubeconfig: Returns KUBECONFIG of a just created cluster
@@ -196,18 +146,22 @@ get-base-config: get-github-config
 	export PATCH=$$(cat $$CONFIG_PATCH | base64 -w 0) || export PATCH="" && \
 	envsubst < ${KOTS_KONFIG} > tmp_config.yml
 
+gcp_storage_credentials := $$(cat gcp-output.json | yq r - 'storage.value.service_account_key_path')
+gcp_registry_credentials := $$(cat gcp-output.json | yq r - 'registry.value.password_file_path')
+gcp_db_credentials := $$(cat gcp-output.json | yq r - 'database.value.service_account_key_path')
+
 storage-config-gcp:
-	export BASE64_GCP_KEY=$$(cat gs-credentials.json | tr -d '\n' | base64 -w 0) && \
+	export BASE64_GCP_KEY=$$(cat $(TF_MOD)/${gcp_storage_credentials} | tr -d '\n' | base64 -w 0) && \
 	envsubst < ./manifests/kots-config-gcp-storage.yaml > tmp_2_config.yml
 	yq m -i tmp_config.yml tmp_2_config.yml
 
 registry-config-gcp:
-	export GCP_KEY=$$(cat gs-credentials.json | tr -d '\n' | jq -Rsa .) && \
+	export GCP_KEY=$$(cat $(TF_MOD)/${gcp_registry_credentials} | tr -d '\n' | jq -Rsa .) && \
 	envsubst < ./manifests/kots-config-gcp-registry.yaml > tmp_4_config.yml
 	yq m -i tmp_config.yml tmp_4_config.yml
 
 db-config-gcp:
-	export BASE64_GCP_KEY=$$(cat mysql-credentials.json | tr -d '\n' | base64 -w 0) && \
+	export BASE64_GCP_KEY=$$(cat $(TF_MOD)/${gcp_db_credentials} | tr -d '\n' | base64 -w 0) && \
 	export DB_INSTANCE=$$(cat gcp-output.json | yq r - 'database.value.instance') && \
 	export DB_PASSWORD=$$(cat gcp-output.json | yq r - 'database.value.password') && \
 	export DB_USER=$$(cat gcp-output.json | yq r - 'database.value.username') && \
@@ -290,7 +244,9 @@ generate-kots-config: cloud_storage = $(if $(findstring external,$(storage)),$(c
 generate-kots-config: cloud_registry = $(if $(findstring external,$(registry)),$(cloud),incluster)
 generate-kots-config: cloud_db = $(if $(findstring external,$(db)),$(cloud),incluster)
 ## generate-kots-config: Generate the kots config based on test config
-generate-kots-config: select-workspace check-env-cloud get-base-config
+generate-kots-config: check-env-cloud get-base-config
+	$(MAKE) -C $(TF_MOD) init
+	$(MAKE) select-workspace WORKDIR=$(TF_MOD)
 	$(MAKE) storage-config-${cloud_storage}
 	$(MAKE) db-config-${cloud_db}
 	$(MAKE) registry-config-${cloud_registry}
@@ -378,15 +334,15 @@ kots-upgrade:
 	@echo "Upgrade gitpod KOTS app to latest"
 	kubectl kots upstream upgrade --kubeconfig=${KUBECONFIG} gitpod -n gitpod --deploy
 
-cloud ?= cluster
-cleanup: $(cloud)-kubeconfig destroy-gitpod tf-init destroy-$(cloud) destroy-workspace destroy-kubeconfig
+cleanup: check-env-cloud $(cloud)-kubeconfig destroy-gitpod destroy-infra destroy-workspace destroy-kubeconfig
 
 cluster-kubeconfig: azure-kubeconfig aws-kubeconfig k3s-kubeconfig gcp-kubeconfig
 
 tf-init:
 	@terraform init
 
-destroy-cluster: destroy-gcp destroy-aws destroy-azure
+destroy-infra: check-env-cloud
+	$(MAKE) -C $(TF_MOD) destroy
 
 destroy-kubeconfig:
 	gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS} --project=sh-automated-tests
@@ -398,22 +354,10 @@ select-workspace:
 	terraform -chdir=${WORKDIR} workspace new $(TF_VAR_TEST_ID) || terraform -chdir=${WORKDIR} workspace select $(TF_VAR_TEST_ID)
 
 destroy-workspace:
-	terraform workspace select default
-	terraform workspace delete $(TF_VAR_TEST_ID) || echo "Couldn't delete workspace, please cleanup manually"
+	terraform -chdir=${TF_MOD} workspace select default
+	terraform -chdir=${TF_MOD} workspace delete $(TF_VAR_TEST_ID) || echo "Couldn't delete workspace, please cleanup manually"
 
-destroy-gcp: destroy-k3s destroy-gke
-
-destroy-k3s: select-workspace
-	[[ -f ${KUBECONFIG} ]] && terraform destroy -target=module.gcp-issuer -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-	[[ -f ${KUBECONFIG} ]] && terraform destroy -target=module.clouddns-externaldns -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-	[[ -f ${KUBECONFIG} ]] && terraform destroy -target=module.certmanager -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-	terraform destroy -target=module.k3s -var kubeconfig=${KUBECONFIG} --auto-approve
-
-destroy-gke: select-workspace
-	[[ -f ${KUBECONFIG} ]] && terraform destroy -target=module.gcp-issuer -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-	[[ -f ${KUBECONFIG} ]] && terraform destroy -target=module.clouddns-externaldns -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-	[[ -f ${KUBECONFIG} ]] && terraform destroy -target=module.certmanager -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-	terraform destroy -target=module.gke -var kubeconfig=${KUBECONFIG} --auto-approve
+destroy-infrastructure:
 
 # Delete the Gitpod namespace and all associated resources.
 #
@@ -423,22 +367,6 @@ destroy-gitpod:
 	[[ -f ${KUBECONFIG} ]] \
 		&& kubectl --kubeconfig=${KUBECONFIG} delete namespace/gitpod --now --timeout 180s \
 		|| true
-
-destroy-aws:
-	$(MAKE) select-workspace
-	terraform destroy -target=module.aws-add-dns-record -var kubeconfig=${KUBECONFIG} --auto-approve
-	ls ${KUBECONFIG} && terraform destroy -target=module.aws-issuer -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-	ls ${KUBECONFIG} && terraform destroy -target=module.aws-externaldns -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-	ls ${KUBECONFIG} && terraform destroy -target=module.certmanager -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-	terraform destroy -target=module.eks -var kubeconfig=${KUBECONFIG} --auto-approve
-
-destroy-azure:
-	$(MAKE) select-workspace
-	ls ${KUBECONFIG} && terraform destroy -target=module.azure-issuer -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-	terraform destroy -target=module.azure-add-dns-record -var kubeconfig=${KUBECONFIG} --auto-approve
-	ls ${KUBECONFIG} && terraform destroy -target=module.azure-externaldns -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-	ls ${KUBECONFIG} && terraform destroy -target=module.certmanager -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-	terraform destroy -target=module.aks -var kubeconfig=${KUBECONFIG} --auto-approve
 
 list-state:
 	terraform state list
